# LAN Services
#
# [ntop](<https://github.com/ntop/docker-ntop>)
# - PF_RING
# - ntopng
# - nProbe

# Docker Compose version
version: '3'

services:
  ntopng-arm:
    build:
      context: ./ntopng
      dockerfile: Dockerfile.arm
    network_mode: host
    volumes:
      - /etc/ntopng:/etc/ntopng:ro
      - /var/lib/ntopng:/var/lib/ntopng
    command: ["/etc/ntopng/ntopng.conf"]
    # command: ["-i ${ETH_IF}","-m 10.0.1.1/24","-n 1","-d /var/lib/ntopng","-q","--community"]
      #- -i ${ETH_IF}
      #- -m 10.0.1.1/24
      #- -n 1
      #- -d /var/lib/ntopng
      #- -q
      #- --community
