version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: jonbackhaus/ntopng
    docker:
      - image: circleci/buildpack-deps:stretch


jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build Docker image
          command: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker build -t $IMAGE_NAME:latest -f ntopng/Dockerfile.arm ntopng
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  test:
    executor: docker-publisher
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Test Docker image
          command: |
            set -x
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker-compose up -d
            curl --fail -s --retry 10 --retry-connrefused http://localhost:3000 || exit 1
  publish:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            COMMIT_SHA1TAG=${CIRCLE_SHA1:0:7}; echo "COMMIT_SHA1TAG=$COMMIT_SHA1TAG"
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_BRANCH
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:$COMMIT_SHA1TAG
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:armv7
            docker push $IMAGE_NAME:latest
            docker push $IMAGE_NAME:armv7
            docker push $IMAGE_NAME:$CIRCLE_BRANCH
            docker push $IMAGE_NAME:$COMMIT_SHA1TAG


workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
          context: default
