version: 2.1
executors:
  executor-docker:
    environment:
      ORG_NAME: jonbackhaus
      IMAGE_NAME: ntopng
    docker:
      - image: cimg/base:2020.01
  executor-buildx:
    machine:
      image: ubuntu-2004:202111-01 
    environment:
      ORG_NAME: jonbackhaus
      IMAGE_NAME: ntopng



jobs:
  job-build-image:
    executor: executor-docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build Docker image
          command: |
            IMAGE_URI=$ORG_NAME/$IMAGE_NAME; echo "IMAGE_URI=$IMAGE_URI"
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker build -t $IMAGE_URI -f ntopng/Dockerfile.arm ntopng
            docker save -o image.tar $IMAGE_URI
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar

  job-build-image-buildx:
    executor: executor-buildx
    steps:
      - checkout
      - run:
          name: Setup buildx and qemu
          command: |
            sudo apt-get update
            sudo apt-get install -y qemu-user-static
            sudo apt-get install -y binfmt-support
      - run:
          name: Check versions
          command: |
            qemu-system-arm -version 
            update-binfmts --version
      - run:
          name: Create Builder
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            docker buildx create --name arm-builder
            docker buildx use arm-builder
            docker buildx inspect --bootstrap
      - run:
          name: Build Docker image
          command: |
            export DOCKER_CLI_EXPERIMENTAL=enabled
            IMAGE_URI=$ORG_NAME/$IMAGE_NAME; echo "IMAGE_URI=$IMAGE_URI"
            docker buildx build --platform linux/arm/v7 -t $IMAGE_URI -f ntopng/Dockerfile.arm ntopng
            docker save -o image.tar $IMAGE_URI
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar


  job-publish-latest:
    executor: executor-docker
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_URI=$ORG_NAME/$IMAGE_NAME; echo "IMAGE_URI=$IMAGE_URI"
            COMMIT_SLUG=${CIRCLE_SHA1:0:7}; echo "COMMIT_SLUG=$COMMIT_SLUG"
            docker load -i /tmp/workspace/image.tar
            docker tag $IMAGE_URI $IMAGE_URI:latest
            docker tag $IMAGE_URI $IMAGE_URI:$COMMIT_SLUG
            docker push $IMAGE_URI:latest
            docker push $IMAGE_URI:$COMMIT_SLUG

  job-publish-branch:
    executor: executor-docker
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            IMAGE_URI=$ORG_NAME/$IMAGE_NAME; echo "IMAGE_URI=$IMAGE_URI"
            docker tag $IMAGE_URI $IMAGE_URI:$CIRCLE_BRANCH
            docker push $IMAGE_URI:$CIRCLE_BRANCH


workflows:
  version: 2
  workflow-commit-main:
    jobs:
      - job-build-image:
          filters:
            branches:
              only: main
      - job-publish-latest:
          requires:
            - "job-build-image"
          context: default
  workflow-commit-branch:
    jobs:
      - job-build-image-buildx:
          filters:
            branches:
              ignore: main
      - job-publish-branch:
          requires:
            - "job-build-image-buildx"
          context: default

  workflow-nightly:
    jobs:
      - job-build-image:
          filters:
            branches:
              only: main
      - job-publish-latest:
          requires:
            - "job-build-image"
          context: default
    triggers:
      - schedule:
          cron: "0 3 * * *"
          filters:
            branches:
              only: main
